### ISSUE TITLE
Python port?

### ISSUE THREAD

**Issue by johndpar** [stuartpittaway/nanodesmapvmonitor#1]
Hi Stuart

Any chance of getting a copy of your Python port please?

I've looked at the sma-bluetooth project (in C of course) but it simply does not meet my needs.

I've also taken a look through your code in this project and like what I see but before I start porting it to Python I thought I'd ask for access to your port. Any improvements/.bugfixes will of course be returned to you.

Kind regards

John

**Comment by stuartpittaway** [comment]
Hi John,

I'm certainly no Python programmer, but if you want to take a look its
attached.  I've deliberately not put this code into the public arena as
it was written in a hurry to run on an embedded Linux box.

Happy for you to improve as long as the original copyright, licence and
headers are kept intact.

Cheers

Stuart.

**Comment by johndpar** [comment]
Hi Stuart

Many thanks and yes headers etc will be kept intact.

However the attachment seems to have gone astray. Could you please try
sending direct to johndpar (at) gmail.com

Thanks again

John

On 21 February 2012 20:47, Stuart Pittaway <
reply@reply.github.com
