### ISSUE TITLE
smanet2packet7 undeclared for getDCValues()

### ISSUE THREAD

**Issue by strykeroz** [stuartpittaway/nanodesmapvmonitor#2]
Hi Stuart

When I uncomment the getDCValues() function I find this parameter is missing.

Is it actually in the declarations under another name?

Thanks
Geoff

**Comment by stuartpittaway** [comment]
I've not run that function for a while, I'd have to go back and look at 
my c# code for ideas!

**Comment by stuartpittaway** [comment]
Fixed in latest release

**Comment by strykeroz** [comment]
Thanks for this mate.  In other news my system got grid-connected yesterday...and failed.  Have people coming out today to look into inverter error.  Gahhhhh!
